[package]
name = "batch_task"
version = "0.1.0"
edition = "2024"

[dependencies]
# crossbeam = "0.8.4"
tokio = { version = "1.45.1", features = ["macros", "rt", "sync", "time"] }
bytes = { version = "1", default-features = false }
anyhow = "1.0.98"
[dev-dependencies]
insta = "*"
